# frozen_string_literal: true

source "https://rubygems.org"

gem "rake"

group :development, :test do
  gem "benchmark-ips"
  gem "pry"
  gem "pry-byebug"
  gem "rspec"
  gem "ruby-lsp"
  gem "ruby-lsp-rspec"
  gem "standard"
end
