# frozen_string_literal: true

require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(:spec)
RuboCop::RakeTask.new

task default: %i[rubocop spec]

desc "Run the solution for a specific day"
task :solve, [:day] do |_, args|
  day_class_file = "lib/day#{args[:day]}"
  require_relative day_class_file

  day_class_name = "Day#{args[:day]}"
  day_class = Object.const_get(day_class_name)

  puts "Solution for Day #{args[:day]}:"
  puts day_class.new.solve
end
